name: Build & Release Spotifi

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build EXE on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # or whatever version you use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install customtkinter

      - name: Build Spotifi.exe with PyInstaller
        run: |
          pyinstaller --clean --icon "NONE" --noconsole --onefile Spotifi.pyw

      - name: Move EXE to output folder
        run: |
          mkdir dist_output
          move dist\Spotifi.exe dist_output\Spotifi.exe

      - name: Bump version and create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          default_bump: patch

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Spotifi v${{ steps.tag_version.outputs.new_tag }}
          body: |
            Auto-generated release.
            (Put changelog info here.)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist_output/Spotifi.exe
